### PR TITLE
Adapted for keynetworks/ztncui

### PR DESCRIPTION
**Pull request by key-networks**

### CODE REVIEW

**Comment by kmahyyg** [comment]
bro, keep in mind, I build it using source code, neither from rpm nor deb. You should use the default expose port from app itself, which means port 3000/tcp is enough... Not 8000/tcp

**Comment by key-networks** [comment]
Sorry for the PR - it was meant to be against my fork.  There is a historic reason for exposing port 8000 - I think others may still be using it in production with custom env files, so I thought it's best to leave it there.

**Comment by key-networks** [comment]
Patrick, is there a reason that you exposed UDP port 9993?  Previously I've never had to do that and it didn't seem to be an issue (I'm guessing because the network controller only needed egress).  Now I have one user reporting that it affects his use case because he was using the ZT client on his host.

**Comment by kmahyyg** [comment]
I personally run ZT in docker, it is NOT necessary for everyone. If you just need run as controller, 9993/udp can be not mapped.

Sent from My iPhone
Proudly using Spark Email

**Comment by key-networks** [comment]
:+1:

**Pull request closed without merging**
